### ISSUE TITLE
Latest stable cargo can't process manifest

### ISSUE THREAD

**Issue by dmilith** [rust-lang-nursery/regex#273] opened 2016-08-08 22:34 UTC
```
error: unable to get packages from source

Caused by:
  failed to parse manifest at `/User/.cargo/registry/src/github.com-1ecc6299db9ec823/regex-0.1.73/Cargo.toml`

Caused by:
  duplicate build target found: `/User/.cargo/registry/src/github.com-1ecc6299db9ec823/regex-0.1.73/src/lib.rs`
```

OS: FreeBSD 11, 64bit, Rust 1.10.0, Cargo 0.13.0 (af4ec39 2016-08-03)

**Comment by BurntSushi** [comment] 2016-08-09 11:33
Looks like a dupe of #272. This bug doesn't affect stable releases AFAIK. cc @alexcrichton

**Closed by BurntSushi** 2016-08-09 11:33 UTC
