### ISSUE TITLE
Nightly cargo cannot parse manifest

### ISSUE THREAD

**Issue by Apanatshka** [rust-lang-nursery/regex#272] opened 2016-08-06 11:29 UTC
# Error
```
error: failed to parse manifest at `[...]/regex/Cargo.toml`

Caused by:
  duplicate build target found: `[...]/regex/src/lib.rs`
```

# Cause

```toml
# Runs unit tests defined inside the regex package.
# Generally these tests specific pieces of the regex implementation.
[[test]]
path = "src/lib.rs"
name = "regex-inline"
```

**Comment by Apanatshka** [comment] 2016-08-06 11:50
(Don't mind the questions in the original issue description, I now get why there are explicit test suites defined)

**Comment by Apanatshka** [comment] 2016-08-06 12:08
# Solution

Remove the offending lines! Looks like a `target/debug/test-somehash` is already generated which runs the same tests.

**Comment by Apanatshka** [comment] 2016-08-06 12:24
I see this change is already done in the `rfc` branch. Can f39985f51795c32e5a84812bc12663ad97698f6 be cherry-picked into master?

**Comment by benaryorg** [comment] 2016-08-06 12:32
I just compared `master` and the latest version tag and there [seem to are changes](https://github.com/rust-lang-nursery/regex/compare/d95d021a7f150a5b513af166f044ba0c51aa31fb...master), that means just cherry-picking on master and publishing the crate might not do that trick entirely.
Even worse when you [compare the latest version and the `rfc` branch](https://github.com/rust-lang-nursery/regex/compare/d95d021a7f150a5b513af166f044ba0c51aa31fb...rfc)!

Would it be possible to cherry pick and rebase to put that commit right after d95d021a7f150a5b513af166f044ba0c51aa31fb (latest version on https://crates.io) and publish that? Just to make it build again.…

**Comment by benaryorg** [comment] 2016-08-07 12:50
It [seems to be fixed on travis-ci.org](https://travis-ci.org/benaryorg/rust-cli_calculator/jobs/150407364) somehow, but I can't seem to get it to work locally.

**Comment by Apanatshka** [comment] 2016-08-08 08:16
I don't see any changes here, so maybe something changed in cargo? 😕

**Comment by BurntSushi** [comment] 2016-08-08 11:04
Yes, there was a Cargo regression: https://internals.rust-lang.org/t/cargo-regression-regex-crate-broken-on-2016-08-05-nightly/3819

**Comment by Apanatshka** [comment] 2016-08-08 14:14
Ok. Looks like it will be a warning for now, and the change is already done in a branch that will be used at some point, I'd be fine with closing this issue. But I'll leave it up to @BurntSushi, since I don't know the system here.

**Comment by dmilith** [comment] 2016-08-08 23:20
https://github.com/rust-lang-nursery/regex/issues/273 - same with "stable" releases - 1.10 + 0.13

**Closed** 2016-09-04 13:39 UTC
