### ISSUE TITLE
Can't compile due to `can't find crate for `rustc_plugin``

### ISSUE THREAD

**Issue by yongqli** [rust-lang-nursery/regex#140] opened 2015-12-07 19:44 UTC
/Users/yongqli/.cargo/registry/src/github.com-0a35038f75765ae4/regex_macros-0.1.24/src/lib.rs:22:1: 22:27 error: can't find crate for `rustc_plugin` [E0463]
    /Users/yongqli/.cargo/registry/src/github.com-0a35038f75765ae4/regex_macros-0.1.24/src/lib.rs:22 extern crate rustc_plugin;

rustc version is `1.6.0-dev (bca27a36e 2015-11-14)`

**Comment by BurntSushi** [comment] 2015-12-08 11:51
Dupe of #138. We track the latest Rust nightlies in this repo. Please update.

**Closed by BurntSushi** 2015-12-08 11:51 UTC
