### ISSUE TITLE
Matching fails if there are more than 10 OR's ( | symbol ) in the regex

### ISSUE THREAD

**Issue by jonimake** [rust-lang-nursery/regex#191] opened 2016-03-28 18:54 UTC
Not much else to say. The following piece of code will fail: 
`assert!(Regex::new(r"1|2|3|4|5|6|7|8|9|10|int").unwrap().is_match("int")); //fails`

While this won't:
`assert!(Regex::new(r"1|2|3|4|5|6|7|8|9|int").unwrap().is_match("int"));`

Edit: this is with 0.1.58 and rust 1.7

**Comment by BurntSushi** [comment] 2016-03-28 20:36
This was fixed in my literal detection refactor: 31a317eadd7d0270dea4ac90b54f5f560514ed01

I added a regression test in: 49577de3d2ac6f7c5695c40b1c6facd72d90c11b

The old code was detecting the following as prefixes: `'1', '2', '3', '4', '5', '6', '7', '8', '9'`. Which is wrong, because it doesn't include `int`.

**Closed by BurntSushi** 2016-03-28 20:36 UTC
