### ISSUE TITLE
Idea: regex-lite crate with drastically reduced compile times

### ISSUE THREAD

**Issue by kamalmarhubi** [rust-lang-nursery/regex#295] opened 2016-11-11 16:56 UTC
There are a lot of use cases where the amazingness of the regex crate is overkill, but you still want regexes. This can be as simple as validating the format of some input. It would be *really* nice to have a crate with minimal dependencies and compile time that could be used in those cases.

Two examples:

- Label validation in Prometheus (https://github.com/pingcap/rust-prometheus/issues/85, https://github.com/pingcap/rust-prometheus/pull/89). The instrumentation library is meant to be used liberally in library crates, and bringing in regex and all its dependencies is a deterrent.
- Parsing semver (https://github.com/steveklabnik/semver-parser/issues/7), which via [rustc_version](https://github.com/Kimundi/rustc-version-rs) is often used in build scripts. This should be as lightweight as possible.

In both cases, a regex is a natural thing to reach for, but the regex crate brings too many dependencies and too large a compile time hit.

I'm imagining a regex-lite crate that only depended on regex-syntax, which itself has no dependencies. An initial version could just support `is_match()` which would already catch a good number of simple use cases.

**Comment by BurntSushi** [comment] 2016-11-11 17:03
> but the regex crate brings too many dependencies

Could you elaborate on why this is causing problems for you?

> too large a compile time hit

`regex` undoubtedly has less than ideal compile times. I'm hoping incremental compilation will help with that.

> I'm imagining a regex-lite crate that only depended on regex-syntax

The availability of `regex-syntax` means anyone can produce such a crate. I personally will not devoting resources to doing that though.

**Comment by kamalmarhubi** [comment] 2016-11-11 17:19
> The availability of `regex-syntax` means anyone can produce such a crate. I personally will not devoting resources to doing that though.

Certainly! I thought this was a good place to discuss the idea, so please do not count it as a request for implementation. Also feel free to close the issue if you think this isn't the right place to discuss it.

> Could you elaborate on why this is causing problems for you?

The two examples I gave above. A bit more background on why I'm trying to excise regex as a dependency in each case:

- [Prometheus instrumentation](https://prometheus.io/docs/practices/instrumentation/) is mean to be applied liberally throughout both binary and library crates. The [metric and label formats are defiend via regexes](https://prometheus.io/docs/concepts/data_model/#metric-names-and-labels), so it's the natural way to express validation. But bringing in regex as a dependency increases compile time for dependent crates that don't use the metrics.

- I've written many build scripts that use rustc_version to conditionally use new features or disable lints. Build scripts should compile quickly. The semver crate currently uses a regex for parsing, which the author finds easier to work with. The downside is that if rustc_version bumped its semver crate requirement to one where regex is used instead, it would slow down build script compilation, increasing build times for any dependent crate.

In both cases, regex makes the library crate author's life easier, but at the expense of compilation time increases for dependent crates. The library author *can* work around this by hand rolling matching code, but a third way could be a nice addition to the ecosystem.

**Comment by BurntSushi** [comment] 2016-11-11 17:22
It sounds like the issue is not dependencies then. It sounds like your only problem is compile times. Therefore, asking for a "dependency free" version of `regex` seems like a misguided request. Every dependency of `regex` compiles quite quickly (try it, `aho-corasick` is probably longest at a few seconds). It is the `regex` crate itself that takes a very long time to compile.

I guess I can leave this issue open, but I personally do not want to maintain or build such a crate. Compile times are certainly legitimate complaint though!

**Comment by kamalmarhubi** [comment] 2016-11-11 17:29
> It sounds like the issue is not dependencies then. It sounds like your only problem is compile times. Therefore, asking for a "dependency free" version of `regex` seems like a misguided request.

Fair point. I adjusted the title.

> I guess I can leave this issue open, but I personally do not want to maintain or build such a crate. Compile times are certainly legitimate complaint though!

Ok! If at any point you want to declutter the issues, go right ahead. :-)

**Comment by kamalmarhubi** [comment] 2016-11-11 17:30
Oh, and is there anything that jumps to mind as good reading for a starting point for a no-frills regex engine?

**Comment by BurntSushi** [comment] 2016-11-11 18:14
There are a few markdown files in this repo. They will point  you to Russ Cox's article series on the topic.

**Comment by BurntSushi** [comment] 2016-11-11 18:46
Sorry, was on mobile, here's the link: https://swtch.com/~rsc/regexp/

This crate was built directly on the ideas in that article.

**Comment by BurntSushi** [comment] 2016-12-28 23:46
I'm going to close this because I think it's beyond the scope of this project.

I will say that I find the idea interesting. It wouldn't be too difficult for an industrious individual to [write a simple compiler](https://github.com/BurntSushi/fst/blob/master/src/regex/compile.rs) and then rip out the [Pike VM matching engine](https://github.com/rust-lang-nursery/regex/blob/master/src/pikevm.rs) from this crate. I think it could be done in less than 2,000 lines. Perhaps even 1,000.

**Closed by BurntSushi** 2016-12-28 23:46 UTC
