### ISSUE TITLE
memchr2() slower than find_singles()?

### ISSUE THREAD

**Issue by birkenfeld** [rust-lang-nursery/regex#184] opened 2016-03-13 08:08 UTC
I made a small benchmark program to compare the new byte-based regexes to pcre.

I noticed that the difference in matching time for `p.th` versus `(?i)p.th` is much larger for regex than for pcre, and tracked it down to here: https://github.com/rust-lang-nursery/regex/blob/raw-bytes/src/literals.rs#L440

Namely, if I remove the `if` and just leave `find_singles`, I get a difference of 48ms instead of 84ms. 
This is when matching ~150MB of Rust source code, _line by line_.

I guess this depends on the haystack size, and only if that gets large enough will `memchr2` be more efficient.  When I remove all the newlines and match again, there is virtually no difference.

**Comment by birkenfeld** [comment] 2016-03-13 08:24
The benchmark program is here: https://github.com/birkenfeld/greptest

**Comment by BurntSushi** [comment] 2016-03-13 15:03
Is there any way you could make it easier to reproduce your results? For example, I don't have your haystack. 150MB is probably too big to share, so I wonder if you can get similar results on a smaller haystack?

---

Here are the benchmarks from the `memchr` crate, running on an i7 3930K:

```
test iterator_memchr   ... bench:       5,272 ns/iter (+/- 10) = 1896 MB/s                                                                                                                     
test iterator_memchr2  ... bench:       7,909 ns/iter (+/- 33) = 1264 MB/s                                                                                                                     
test iterator_memchr3  ... bench:       7,902 ns/iter (+/- 17) = 1265 MB/s                                                                                                                     
test iterator_memrchr  ... bench:       5,273 ns/iter (+/- 11) = 1896 MB/s                                                                                                                     
test optimized_memchr  ... bench:         202 ns/iter (+/- 0) = 49504 MB/s                                                                                                                     
test optimized_memchr2 ... bench:       1,711 ns/iter (+/- 4) = 5844 MB/s                                                                                                                      
test optimized_memchr3 ... bench:       3,267 ns/iter (+/- 10) = 3060 MB/s                                                                                                                     
test optimized_memrchr ... bench:         197 ns/iter (+/- 0) = 50761 MB/s
```

Here's the benchmark code for `iterator_memchr2`:

```rust
#[bench]
fn iterator_memchr2(b: &mut test::Bencher) {
    let haystack = bench_data();
    let (needle1, needle2) = (b'a', b'b');
    b.iter(|| {
        assert!(haystack.iter().position(|&b| {
            b == needle1 || b == needle2
        }).is_none());
    });
    b.bytes = haystack.len() as u64;
}
```

This doesn't quite correspond to `find_singles` though. So if I add a benchmark that uses regex's `find_singles`:

```rust
#[bench]
fn manual_memchr2(b: &mut test::Bencher) {
    fn find_singles(
        sparse: &[bool],
        text: &[u8],
    ) -> Option<(usize, usize)> {
        for (hi, &b) in text.iter().enumerate() {
            if sparse[b as usize] {
                return Some((hi, hi+1));
            }
        }
        None
    }

    let haystack = bench_data();
    let mut sparse = vec![false; 256];
    sparse[b'a' as usize] = true;
    sparse[b'b' as usize] = true;
    b.iter(|| {
        assert!(find_singles(&sparse, &haystack).is_none());
    });
    b.bytes = haystack.len() as u64;
}
```

then I get:

```
test iterator_memchr2  ... bench:       7,911 ns/iter (+/- 48) = 1264 MB/s
test manual_memchr2    ... bench:       5,274 ns/iter (+/- 14) = 1896 MB/s
test optimized_memchr2 ... bench:       1,712 ns/iter (+/- 8) = 5841 MB/s
```

All signs point to `memchr2` being quite a bit faster. With that said, note that `bench_data` is:

```rust
fn bench_data() -> Vec<u8> { iter::repeat(b'z').take(10000).collect() }
```

So these benchmarks are only testing the full raw speed of `memchr` over large haystacks. A different benchmark more appropriate for this issue would be one that compares finding all matches in a haystack with some matches.

---

With all that said, your issue is really an instance of a larger problem, which is that I don't fully grok the performance characteristics of the `memchr` variants versus the more naive approach because I haven't done systematic benchmarking yet. At the very least, it seems safe to conclude that the `memchr` variants are superior when there *isn't* a match, which is a very important use case to optimize. On the other hand, doing prefix search *at all* even when there is a prefix to be matched might end up taking longer if the prefix matches very frequently.

For example, you can see an instance of me flailing incompetently right here: https://github.com/rust-lang-nursery/regex/blob/raw-bytes/src/literals.rs#L525

Some thoughts for the future:

1. We need more systematic benchmarking around literal searching. This should ideally include an additional can of worms that is non-western text. (For example, given a three byte UTF-8 sequence, it's probably better to `memchr` the last byte in the sequence than the first.)
2. No matter what we do, we are hopelessly hosed in some number of cases because the analysis usually starts with, "If the haystack looks like X, then Y..." We don't actually know what the haystack looks like at compile time, so we'll always choose a sub-optimal strategy for some inputs. The key is figuring out what's common, which is yet another problem with no concrete answers.

---

How is `regex` doing vs. PCRE?

**Comment by birkenfeld** [comment] 2016-03-13 15:17
Sorry, should have been more concrete. The haystack is 
```
cat rust-clone/**/*.rs > hs1
cat hs1 hs1 hs1 hs1 hs1 hs1 > haystack
```
where `rust-clone` is rust-lang/rust. The `haystack` now has around 150 MB, with around 4.3 million lines.

With this haystack, the results of `greptest` with the two patterns on my machine are:

 | `p.th` | `(?i)p.th`
--- | ------ | ----------
regex, memchr2 | 472 | 564
regex, find_single | 476 | 521 ms
pcre, no jit | 513 | 544
pcre, jit | 416 | 425

So `regex` is mostly beating PCRE without JIT, which is already very nice!

**Comment by birkenfeld** [comment] 2016-03-13 15:21
(Note that the average line, and therefore regex haystack, length in the file is only 32 characters.)

**Comment by BurntSushi** [comment] 2016-03-13 15:24
@birkenfeld Thanks. This issue will probably linger for a bit until I can figure out how to benchmark this stuff better, but data points help.

Also, have you seen the microbenchmarks? https://gist.github.com/anonymous/e4fe1a265bfb4043620b --- `regex` does quite a bit better there against PCRE (**with the JIT enabled**). The key observation is that many of the benchmarks are on a bigger haystack, which tends to move any constant overhead into the noise. Many of the benchmarks where PCRE does better are indeed on smaller haystacks, like in your case.

I am working on a `grep` in Rust, and one of the tricks there is to completely forgo the idea of "line by line" searching. It's much faster to just run the regex on the `&[u8]` directly, but this is itself subject to a number gotchas and isn't always possible...

**Comment by birkenfeld** [comment] 2016-03-13 15:40
Yeah, my eventual use case is an `ack`/`ag` like tool: https://github.com/birkenfeld/ruthenium
With PCRE the runtime is currently on par with ag (with the advantage that it doesn't crash) - but I haven't fully implemented all options.

I guess I'll try the "match on the whole buffer" strategy too. Especially with few matches it should be a big win.

**Comment by BurntSushi** [comment] 2016-03-13 19:02
Another idea to try here is that we could disable prefix optimizations when the haystack is below a certain (short) length.

**Comment by BurntSushi** [comment] 2016-12-29 01:02
I'm going to close this issue because there's nothing specifically actionable here.

There is definitely some fruit to be gained by perhaps coming up with a more principled framework for reasoning about literal optimizations. In particular, all literal optimizations boil down to heuristics. They're almost never ubiquitous wins because they trade predictable performance for fast skipping, based on the assumption that literal matches are rare. It tends to work well in practice, but when it comes time to actually pick an optimization to use, [it's basically just a bunch of guesses](https://github.com/rust-lang-nursery/regex/blob/b2419df8fdc4df6fcd33d1bd303581b2491ca113/src/literals.rs#L201-L242).

**Closed by BurntSushi** 2016-12-29 01:02 UTC
